version: '2'
services:
    httpbin:
      image: docker.io/kennethreitz/httpbin:latest
      ports:
        - '38282:80'
      networks:
        static-network:
          ipv4_address: 172.21.93.93
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.21.0.0/16
